server:
  port: 6001

logging:
  config: classpath:logback-boot.xml
eureka:
  instance:
    metadata-map:
      zone: ${MYZONE:zone1}  # zone1
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    prefer-ip-address: true
    #Eureka客户需要多长时间发送心跳给eureka服务器，表明它仍然活着,默认为30 秒
    lease-renewal-interval-in-seconds: 5
    #Eureka服务器在接收到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除，默认为90秒
    lease-expiration-duration-in-seconds: 10
    #使用IP和端口作为实例名称
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    #表示eureka client间隔多久去拉取服务注册信息，默认为30秒，对于gateway-api，如果要迅速获取服务注册状态，可以缩小该值，比如5秒
    #registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://192.168.30.158:9001/eureka/
    fetch-registry: true

spring:
  application:
    name: test-demo
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      max-active: 50
      #min-idle: 10
      max-wait: 180000 #Default value is 30000 (30 seconds)60000->180000
      time-between-eviction-runs-millis: 600000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒，default value is 5000 (5 seconds)->60000-600000
      min-evictable-idle-time-millis: 3600000 #配置一个连接在池中最小生存的时间，单位是毫秒，default value is 60000 (60 seconds)->300000-3600000
      pool-prepared-statements: false #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
mybatis:
  #需要配合自动扫描Mappers包
  type-aliases-package: com.lr.service.testdemo.dao
  #mappers.xml所在位置
  mapper-locations: classpath:mappers/*.xml
  config-location: classpath:mybatis-config.xml
